# Generated by Django 5.1.6 on 2025-02-21 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('UPCOMING', 'upcoming'), ('ONGOING', 'ongoing'), ('COMPLETED', 'completed')], default='UPCOMING', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CONF', 'Conference'), ('MEETUP', 'Meetup'), ('WORKSHOP', 'Workshop')], default='MEETUP', max_length=50)),
                ('asset', models.ImageField(blank=True, default='events_asset/default_img.jpg', null=True, upload_to='events_asset')),
                ('notes', models.TextField(blank=True, null=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ManyToManyField(related_name='rsvps', to='events.event')),
                ('user', models.ManyToManyField(related_name='rsvps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
