# Generated by Django 5.1.6 on 2025-02-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('UPCOMING', 'upcoming'), ('ONGOING', 'ongoing'), ('COMPLETED', 'completed')], default='UPCOMING', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CONF', 'Conference'), ('MEETUP', 'Meetup'), ('WORKSHOP', 'Workshop')], default='MEETUP', max_length=50)),
                ('asset', models.ImageField(blank=True, default='events_asset/default_img.jpg', null=True, upload_to='events_asset')),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
