# Generated by Django 5.1.6 on 2025-02-24 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventdetail',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='events.event'),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='event',
            field=models.ManyToManyField(related_name='rsvps', to='events.event'),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='user',
            field=models.ManyToManyField(related_name='rsvps', to=settings.AUTH_USER_MODEL),
        ),
    ]
